 name:Pompieri
 version: ${version}
 description: Plugin per metropolis, sviluppato da Tommy_T0mmY 
 author: Tommy_T0mmY #Non fare il furbo, togli i tuoi crediti dalla repository
 main: com.github.tommyt0mmy.firefighter.FireFighter
 prefix: Pompieri
 api-version: 1.13
 commands:
   firefighter:
     usage: "Usage: /<command> [command name|page] ..."
     description: Shows the help menu
   fireset:
     usage: "Usage: /<command> [setwand|addmission|editmission|deletemission] ..."
     description: Sets,edits or deletes missions
   firetool:
     usage: "Usage: /<command>"
     description: Gives you a fire extinguisher
